apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-k8s
          image: gayanj/hello-k8s
          ports:
            - name: hello-k8s-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: hello-k8s-port
            initialDelaySeconds: 15
            timeoutSeconds: 30
