apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s-pod
  labels:
    app: hello-k8s
spec:
  containers:
    - name: hello-k8s
      image: gayanj/hello-k8s
      ports:
        - name: hello-k8s-port
          containerPort: 3000
