apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
spec:
  ports:
  - port: 80
    nodePort: 31001
    targetPort: hello-k8s-port
    protocol: TCP
  selector:
    app: hello-k8s
  type: NodePort
